# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block, everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

export EDITOR=/usr/local/bin/nvim
export VISUAL=/usr/local/bin/nvim

bindkey -M vicmd '?' history-incremental-search-backward

export VIRTUALENVWRAPPER_PYTHON=/Users/jay_thompson/.pyenv/shims/python
export VIRTUALENVWRAPPER_VIRTUALENV_ARGS='--no-site-packages'
export VIRTUALENVWRAPPER_VIRTUALENV=/usr/local/bin/virtualenv
export PIP_VIRTUALENV_BASE=$WORKON_HOME
export PIP_RESPECT_VIRTUALENV=true
source /usr/local/bin/virtualenvwrapper.sh

export PATH="$PATH:$HOME/.rvm/bin:/opt/chefdk:$HOME/bin:$HOME/.cargo/bin" # Add RVM to PATH for scripting
export PATH="/usr/local/opt/coreutils/libexec/gnubin:$PATH"

source /usr/local/share/zsh/site-functions/_aws

test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"

test -e "${HOME}/.secret" && source "${HOME}/.secret"

alias vim=/usr/local/bin/nvim

alias ll='ls -la --color=auto'

alias kube='kubectl'

alias po='poetry'

alias pdev='pipenv install --dev pytest ipython yapf feedparser jedi pylint flake8 isort autoimport reorder-python-imports'
alias podev='poetry add --dev pytest ipython yapf feedparser jedi pylint flake8 isort autoimport reorder-python-imports'

alias dcu='docker-compose up -d'
alias dcd='docker-compose down -v'
alias dcb='docker-compose build'

alias dstop='docker stop $(docker ps -aq)'

eval "$(direnv hook zsh)"

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# fh - repeat history
fh() {
  print -z $( ([ -n "$ZSH_NAME" ] && fc -l 1 || history) | fzf +s --tac | sed 's/ *[0-9]* *//')
}

fzf-safari-browser-history() {
  local cols sep
  cols=$(( COLUMNS / 3 ))
  sep='{::}'

  sudo cp -f ~/Library/Safari/History.db /tmp/h

  sqlite3 -separator $sep /tmp/h \
    "select substr(id, 1, $cols), url
     from history_items order by visit_count_score desc" |
  awk -F $sep '{printf "%-'$cols's  \x1b[36m%s\x1b[m\n", $1, $2}'  |
  fzf --ansi --multi | sed 's#.*\(https*://\)#\1#' | xargs open
}

if [ /usr/local/bin/kubectl ]; then source <(kubectl completion zsh); fi
source ~/.kubectl_fzf.plugin.zsh

if [ /usr/local/bin/helm ]; then source <(helm completion zsh); fi

export NVM_DIR="$HOME/.nvm"
[ -s "/usr/local/opt/nvm/nvm.sh" ] && . "/usr/local/opt/nvm/nvm.sh"  # This loads nvm
[ -s "/usr/local/opt/nvm/etc/bash_completion" ] && . "/usr/local/opt/nvm/etc/bash_completion"  # This loads nvm bash_completion


function iterm2_print_user_vars() {
  iterm2_set_user_var gitBranch $((git branch 2> /dev/null) | grep \* | cut -c3-)
  iterm2_set_user_var home $(echo -n "$HOME")
  iterm2_set_user_var billing_code $(echo -n "$BILLING_CODE")
  iterm2_set_user_var cost_center $(echo -n "$COST_CENTER")
  iterm2_set_user_var project $(echo -n "$PROJECT")
  iterm2_set_user_var kubecontext $(kubectx -c)
  iterm2_set_user_var kubenamespace $(kubens -c)
}

eval "$(pyenv init -)"

export PATH="${KREW_ROOT:-$HOME/.krew}/bin:$PATH"

fpath+=~/.zfunc

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

export DOCKER_BUILDKIT=1
export COMPOSE_DOCKER_CLI_BUILD=1

setopt IGNORE_EOF
